### ISSUE TITLE
FTL Failed initialising smoothstreams error="token: get token: validate token response: 404 Not Found"

### ISSUE THREAD

**Issue by neil123454** [l3uddz/sstv#14]
Hi guys
Trying to run this on my RPI
Managed to get it loaded into on my rpi via portainer but keep getting this error

My config file looks like this:

public_url: http://http://192.168.1.80/:1411  - this is the rpi address and the docker image is running as host (so I havent made it complicated with any reverse proxies etc)
smoothstreams:
  username: xxx@gmail.com
  password: xxx
  site: view247
  server: deu

But it will output:

FTL Failed initialising smoothstreams error="token: get token: validate token response: 404 Not Found"

**Comment by neil123454** [comment]
anyone?

**Comment by ben-burns** [comment]
@neil123454 Your `public_url` looks wrong.  Try `http://192.168.1.80:1411` instead.

**Comment by l3uddz** [comment]
Also would make sure your Config has proper yml formatting like shown in the example Config (indentations are important)

**Comment by neil123454** [comment]
So I have changed the host name but still getting the same error now on a x86 system. I have attached the yml fil

I have tried using both the username for live 247 and the email for the account

https://easyupload.io/tibbk8

**Comment by l3uddz** [comment]
Config looks ok.

Only thing I can suggest is try running with -vv to see if theres any additional context. Looks like the token url is not correct for the site

**Comment by neil123454** [comment]
Seems to be the same error with YAP on windows. Must be an issue with the login. Strange as the same details work on the web version. Thanks for the help
